### PR TITLE
Add terminal colors for VSCode terminal

### PR DESCRIPTION
**Pull request by yylian**
@tathran this should add the correct colors, but it does not look perfect. You should have a look too.

### CODE REVIEW

**Comment by yylian** [comment]
Sorry for the force pushes, I had way too many typos in the commit messages.

**Comment by ctrl-dlahr** [comment]
Hey @yylian There are two things that I think should be changed:

1. I use block cursor and it is invisible (likely same color as background) and should be the same as set in the current color scheme i.e. `#ecf0c1`

2. The selection highlight color is a little hard to see and I'd prefer it matched what is set in the current color scheme (I believe it is this color: `#200053`)

Everything else looks fantastic. Just two minor things if you don't mind fixing them. If you disagree I am happy to discuss. I am mostly basing this on my own tastes and for those two I find it hard to work with.

Thanks so much for the PR!

**Comment by yylian** [comment]
Hey, sorry for the delay, have swtiched them, should be good to use now. 👍

**Comment by ghost** [comment]
Just FYI, I updated the bg color because I wanted it to more closely match spaceducks color. I also like it to be the same as the current editor. If you wanted to tweak it for yourself, please see: <https://github.com/tathran/spaceduck-vscode/issues/3#issuecomment-805460989>

Thanks for your work on this!

**Pull request merged**
